/*==================================================================================================
*   Project              : RTD AUTOSAR 4.7
*   Platform             : CORTEXM
*   Peripheral           : FLEXCAN
*   Dependencies         : 
*
*   Autosar Version      : 4.7.0
*   Autosar Revision     : ASR_REL_4_7_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 3.0.0
*   Build Version        : S32K1_RTD_3_0_0_QLP02_D2505_ASR_REL_4_7_REV_0000_20250530
*
*   Copyright 2020-2025 NXP
*
*   NXP Confidential and Proprietary. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/
/*==================================================================================================
==================================================================================================*/
/*
@brief   The consistency of the configuration must be checked by the configuration tool(s).
@brief   (SWS_Can_00022) The code configuration of the Can module is CAN controller specific.
         If the CAN controller is sited on-chip, the code generation tool for the Can module is Controller specific.
         If the CAN controller is an external device the generation tool must not be Controller specific.
@brief   (SWS_Can_00024) The valid values that can be configured are hardware dependent.
         Therefore the rules and constraints can't be given in the standard.
         The configuration tool is responsible to do a static configuration checking, also regarding dependencies between modules (i.e. Port driver, MCU driver etc.)
*/

#ifndef CAN_43_FLEXCAN_CFG_H
#define CAN_43_FLEXCAN_CFG_H

/**
*   @file    Can_43_FLEXCAN_Cfg.h
*   @version 3.0.0
*
*   @brief   AUTOSAR Can_43_FLEXCAN - module interface
*   @details Configuration settings generated by user settings.
*
*   @addtogroup CAN_43_FLEXCAN_DRIVER
*   @{
*/

#ifdef __cplusplus
extern "C"{
#endif

/**
* @page misra_violations MISRA-C:2012 violations
*
* @section [global]
* Violates MISRA 2012 Required Rule 5.1, External identifiers shall be distinct.
* The used compilers use more than 31 chars for identifiers.
*
* @section [global]
* Violates MISRA 2012 Required Rule 5.2, Identifiers declared in the same scope and name space shall be distinct.
* The used compilers use more than 31 chars for identifiers.
*
* @section [global]
* Violates MISRA 2012 Required Rule 5.4, Macro identifiers shall be distinct.
* The used compilers use more than 31 chars for identifiers.
*
* @section [global]
* Violates MISRA 2012 Required Rule 5.5, Identifiers shall be distinct from macro names.
* The used compilers use more than 31 chars for identifiers.
*
* @section Can_43_FLEXCAN_Cfg_h_REF_1
* Violates MISRA 2012 Advisory Rule 2.5, A project should not contain unused macro declarations.
* Some macro are required by ASR even they are not use in MCAL layer
*
* @section Can_43_FLEXCAN_Cfg_h_REF_2
* Violates MISRA 2012 Advisory Rule 4.9, A function should be used in preference to a function-like macro where they are interchangeable.
* Function like macro are used to reduce code complexity
*/

/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/
[!AUTOSPACING!]
[!INDENT "0"!]
[!IF "var:defined('postBuildVariant')"!]
    [!LOOP "variant:all()"!]
        #include "Can_43_FLEXCAN_[!"."!]_PBcfg.h"
    [!ENDLOOP!]
[!ELSE!]
    #include "Can_43_FLEXCAN_PBcfg.h"
[!ENDIF!]
[!NOCODE!]
    [!INCLUDE "Can_43_FLEXCAN_VersionCheck_Inc.m"!]
    [!INCLUDE "Can_43_FLEXCAN_PluginMacro.m"!]
[!ENDNOCODE!]
/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
#define CAN_43_FLEXCAN_VENDOR_ID_CFG_H                     43
#define CAN_43_FLEXCAN_MODULE_ID_CFG_H                     80
#define CAN_43_FLEXCAN_AR_RELEASE_MAJOR_VERSION_CFG_H      4
#define CAN_43_FLEXCAN_AR_RELEASE_MINOR_VERSION_CFG_H      7
#define CAN_43_FLEXCAN_AR_RELEASE_REVISION_VERSION_CFG_H   0
#define CAN_43_FLEXCAN_SW_MAJOR_VERSION_CFG_H              3
#define CAN_43_FLEXCAN_SW_MINOR_VERSION_CFG_H              0
#define CAN_43_FLEXCAN_SW_PATCH_VERSION_CFG_H              0
/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/
[!IF "var:defined('postBuildVariant')"!]
    [!LOOP "variant:all()"!]
        /* Check if header file and Can_43_FLEXCAN_[!"."!]_PBcfg.h configuration header file are of the same vendor */
        #if (CAN_43_FLEXCAN_VENDOR_ID_[!"text:toupper(.)"!]_PBCFG_H != CAN_43_FLEXCAN_VENDOR_ID_CFG_H)
            #error "Can_43_FLEXCAN_[!"."!]_PBcfg.h and Can_43_FLEXCAN_Cfg.h have different vendor ids"
        #endif
         /* Check if header file and Can_43_FLEXCAN_[!"."!]_PBcfg.h configuration header file are of the same Autosar version */
        #if ((CAN_43_FLEXCAN_AR_RELEASE_MAJOR_VERSION_[!"text:toupper(.)"!]_PBCFG_H != CAN_43_FLEXCAN_AR_RELEASE_MAJOR_VERSION_CFG_H) || \
             (CAN_43_FLEXCAN_AR_RELEASE_MINOR_VERSION_[!"text:toupper(.)"!]_PBCFG_H != CAN_43_FLEXCAN_AR_RELEASE_MINOR_VERSION_CFG_H) || \
             (CAN_43_FLEXCAN_AR_RELEASE_REVISION_VERSION_[!"text:toupper(.)"!]_PBCFG_H != CAN_43_FLEXCAN_AR_RELEASE_REVISION_VERSION_CFG_H) \
            )
            #error "AutoSar Version Numbers of Can_43_FLEXCAN_[!"."!]_PBcfg.h and Can_43_FLEXCAN_Cfg.h are different"
        #endif
        /* Check if header file and Can_43_FLEXCAN_[!"."!]_PBcfg.h configuration header file are of the same software version */
        #if ((CAN_43_FLEXCAN_SW_MAJOR_VERSION_[!"text:toupper(.)"!]_PBCFG_H != CAN_43_FLEXCAN_SW_MAJOR_VERSION_CFG_H) || \
             (CAN_43_FLEXCAN_SW_MINOR_VERSION_[!"text:toupper(.)"!]_PBCFG_H != CAN_43_FLEXCAN_SW_MINOR_VERSION_CFG_H) || \
             (CAN_43_FLEXCAN_SW_PATCH_VERSION_[!"text:toupper(.)"!]_PBCFG_H != CAN_43_FLEXCAN_SW_PATCH_VERSION_CFG_H) \
            )
            #error "Software Version Numbers of Can_43_FLEXCAN_[!"."!]_PBcfg.h and Can_43_FLEXCAN_Cfg.h are different"
        #endif
    [!ENDLOOP!]
[!ELSE!]
    /* Check if header file and Can_43_FLEXCAN_PBcfg.h configuration header file are of the same vendor */
    #if (CAN_43_FLEXCAN_VENDOR_ID_PBCFG_H != CAN_43_FLEXCAN_VENDOR_ID_CFG_H)
        #error "Can_43_FLEXCAN_PBcfg.h and Can_43_FLEXCAN_Cfg.h have different vendor ids"
    #endif
     /* Check if header file and Can_43_FLEXCAN_PBcfg.h configuration header file are of the same Autosar version */
    #if ((CAN_43_FLEXCAN_AR_RELEASE_MAJOR_VERSION_PBCFG_H != CAN_43_FLEXCAN_AR_RELEASE_MAJOR_VERSION_CFG_H) || \
         (CAN_43_FLEXCAN_AR_RELEASE_MINOR_VERSION_PBCFG_H != CAN_43_FLEXCAN_AR_RELEASE_MINOR_VERSION_CFG_H) || \
         (CAN_43_FLEXCAN_AR_RELEASE_REVISION_VERSION_PBCFG_H != CAN_43_FLEXCAN_AR_RELEASE_REVISION_VERSION_CFG_H) \
        )
        #error "AutoSar Version Numbers of Can_43_FLEXCAN_PBcfg.h and Can_43_FLEXCAN_Cfg.h are different"
    #endif
    /* Check if header file and Can_43_FLEXCAN_PBcfg.h configuration header file are of the same software version */
    #if ((CAN_43_FLEXCAN_SW_MAJOR_VERSION_PBCFG_H != CAN_43_FLEXCAN_SW_MAJOR_VERSION_CFG_H) || \
         (CAN_43_FLEXCAN_SW_MINOR_VERSION_PBCFG_H != CAN_43_FLEXCAN_SW_MINOR_VERSION_CFG_H) || \
         (CAN_43_FLEXCAN_SW_PATCH_VERSION_PBCFG_H != CAN_43_FLEXCAN_SW_PATCH_VERSION_CFG_H) \
        )
        #error "Software Version Numbers of Can_43_FLEXCAN_PBcfg.h and Can_43_FLEXCAN_Cfg.h are different"
    #endif
[!ENDIF!]
/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/
/**
*   @brief      Enable/Disable Precompile Support
*/
#define CAN_43_FLEXCAN_PRECOMPILE_SUPPORT[!WS "4"!][!IF "IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile' and (variant:size()<=1)"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Number of Can Controller Support
*/
#define CAN_43_FLEXCAN_HWCONTROLLER_SUPPORT[!WS "4"!][!"num:i(ecu:get('Can.CanConfigSet.CanController'))"!]U

/**
*   @brief      Controller unsed
*/
#define CAN_43_FLEXCAN_CONTROLLER_UNUSED[!WS "4"!]((uint8)0xFFU)

/**
*   @brief      The definition represent for Message buffer index which not assigned for any Hw Object
*/
#define CAN_43_FLEXCAN_HWOBJ_UNMAPPED[!WS "4"!]((Can_HwHandleType)0xFFFFU)

/**
*   @brief      The definition represent for number of ECUC partition configured.
*/
[!NOCODE!]
    [!VAR "maxPartitionDefConfig" = "num:i(1)"!]
    [!IF "CanGeneral/CanMultiPartitionSupport = 'true'"!]
        [!IF "node:exists(as:modconf('EcuC')[1]/EcucPartitionCollection/*[1]/EcucPartition)"!]
            [!VAR "maxPartitionDefConfig" = "num:i(count(as:modconf('EcuC')[1]/EcucPartitionCollection/*[1]/EcucPartition/*))"!]
        [!ENDIF!]
    [!ENDIF!]
[!ENDNOCODE!]
#define CAN_43_FLEXCAN_MAX_PARTITIONS[!WS "4"!][!"$maxPartitionDefConfig"!]U

/**
*   @brief      Number Of Hw Message Buffer support
*/
#define CAN_43_FLEXCAN_HWMB_COUNT[!WS "4"!]((uint8)[!"num:i(ecu:get('Can.CanConfigSet.CanMB'))"!]U)

[!SELECT "CanGeneral"!]
/**
 *  @brief      The definition of TimeStamp Enable Support for Hw Objects
 */
#define CAN_43_FLEXCAN_TIMESTAMP_ENABLE[!WS "4"!][!IF "(ecu:get('Can.CanConfigSet.TimeStampSupport')='STD_ON') and node:exists(CanTimeStamp)"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*  @brief      Definition of external timer used for timestamp
*/
[!VAR "external_timer_used" = "0"!]
[!IF "(ecu:get('Can.CanConfigSet.TimeStampSupport')='STD_ON') and node:exists(CanTimeStamp)"!]
    [!IF "ecu:get('Can.CanConfigSet.TimeStampSrcList') != '' and CanTimeStamp/HRTimeStampCapturePoint != 'FLEXCAN_TIMESTAMPCAPTURE_DISABLE'"!]
    [!NOCODE!]
        [!VAR "HR_Time_Src" = "string(CanTimeStamp/TimestampHRTimeSource)"!]
        [!VAR "DerivativeName" = "substring-before(as:modconf("Resource")[1]/ResourceGeneral/ResourceSubderivative,'_')"!]
        [!IF "contains($DerivativeName, 's32n5')"!]
            [!VAR "CrsCanControllerUseTimestamp" = "0"!]
            [!VAR "FssCanControllerUseTimestamp" = "0"!]
            [!LOOP "../CanConfigSet/CanController/*"!]
                [!IF "node:value(./CanHwChannel) != 'FLEXCAN_24'"!]
                    [!IF "node:exists(./CanControllerTimeStamp)"!]
                        [!VAR "CrsCanControllerUseTimestamp" = "1"!]
                    [!ENDIF!]
                [!ELSE!]
                    [!IF "node:exists(./CanControllerTimeStamp)"!]
                        [!VAR "FssCanControllerUseTimestamp" = "1"!]
                    [!ENDIF!]
                [!ENDIF!]
            [!ENDLOOP!]
            [!IF "($CrsCanControllerUseTimestamp = 1) and ($FssCanControllerUseTimestamp = 1)"!]
                [!ERROR!]
                    Due to the limitation of the driver, the CRS Can controllers (FLEXCAN_0 to FLEXCAN_23) and FSS Can controller (FLEXCAN_24) should not be enabled timestamp feature at the same time!
                    Only enable CanControllerTimeStamp for the CRS Can controllers (FLEXCAN_0 to FLEXCAN_23) or FSS Can controller (FLEXCAN_24).
                [!ENDERROR!]
            [!ELSE!]
                [!SELECT "node:ref(CanTimeStamp/CanTimeStampExternalTimerReference)"!]
                    [!IF "contains($HR_Time_Src, 'STM')"!]
                        [!IF "($CrsCanControllerUseTimestamp = 1)"!]
                            [!ERROR!]
                                The CRS Can controllers (FLEXCAN_0 to FLEXCAN_23) are enabled timestamp feature but TimestampHRTimeSource selected is [!"$HR_Time_Src"!] which is not support for these controllers!
                            [!ENDERROR!]
                        [!ELSEIF "($FssCanControllerUseTimestamp = 1) and not(contains(node:ref(GptModuleRef)/../../GptStmModule, 'FSS_STM'))"!]
                            [!ERROR!]
                                The referred GptChannelConfiguration must be a FSS_STM hardware instance when enabling timestamp for FSS Can controller (FLEXCAN_24)!
                            [!ENDERROR!]
                        [!ENDIF!]
                    [!ENDIF!]
                    [!IF "contains($HR_Time_Src, 'STIMER')"!]
                        [!IF "($CrsCanControllerUseTimestamp = 1) and not(contains(node:ref(GptModuleRef)/../../GptStimerModule, 'CRS_STIMER'))"!]
                            [!ERROR!]
                                The referred GptChannelConfiguration must be a CRS_STIMER hardware instance when enabling timestamp for CRS Can controllers (FLEXCAN_0 to FLEXCAN_23)!
                            [!ENDERROR!]
                        [!ELSEIF "($FssCanControllerUseTimestamp = 1) and not(contains(node:ref(GptModuleRef)/../../GptStimerModule, 'FSS_HKI_STIMER'))"!]
                            [!ERROR!]
                                The referred GptChannelConfiguration must be a FSS_HKI_STIMER hardware instance when enabling timestamp for FSS Can controller (FLEXCAN_24)!
                            [!ENDERROR!]
                        [!ENDIF!]
                    [!ENDIF!]
                [!ENDSELECT!]
            [!ENDIF!]
        [!ELSEIF "contains($DerivativeName, 's32n7')"!]
            [!// To check for S32N7 platform
        [!ENDIF!]
    [!ENDNOCODE!]
        [!IF "contains($HR_Time_Src, 'MAC')"!]
            #define CAN_43_FLEXCAN_TS_MAC_USED
            [!VAR "mac_instance" = "0"!]
            [!IF "contains($HR_Time_Src, 'MAC1')"!]
                [!VAR "mac_instance" = "1"!]
            [!ENDIF!]
            #define CAN_43_FLEXCAN_TS_MAC_INSTANCE [!"num:i($mac_instance)"!]U
        [!ELSEIF "contains($HR_Time_Src, 'STM')"!]
            [!VAR "external_timer_used" = "1"!]
            [!SELECT "node:ref(CanTimeStamp/CanTimeStampExternalTimerReference)"!]
                [!VAR "Gpt_Channel_Tick_Frequency" = "GptChannelTickFrequency"!]
                [!VAR "GptChannelId" = "GptChannelId"!]
                [!VAR "StmInstance" = "substring-after(node:ref(GptModuleRef)/../../GptStmModule, 'STM_')"!]
                [!VAR "StmChannel" = "substring-after(node:ref(GptModuleRef)/GptStmChannel, 'CH_')"!]
            [!ENDSELECT!]
            [!IF "(CanTimeStamp/CanTimeStampRequiredAccuracy) != (1000000000 div $Gpt_Channel_Tick_Frequency)"!]
                [!WARNING!]
                    To convert timestamp value to nanosecond, CanTimeStampRequiredAccuracy should be [!"(1000000000 div $Gpt_Channel_Tick_Frequency)"!](1Ghz/GptChannelTickFrequency)
                [!ENDWARNING!]
            [!ENDIF!]
            #define CAN_43_FLEXCAN_TS_STM_USED
            #define CAN_43_FLEXCAN_TS_GPT_CHANNEL_ID ([!"num:i($GptChannelId)"!]U)
            #define CAN_43_FLEXCAN_TS_STM_INSTANCE ([!"num:i($StmInstance)"!]U)
            #define CAN_43_FLEXCAN_TS_STM_CHANNEL  ([!"num:i($StmChannel)"!]U)
            #define CAN_43_FLEXCAN_TS_STM_TARGETTIME  ([!"num:i($Gpt_Channel_Tick_Frequency)"!]U)
            #define CAN_43_FLEXCAN_TS_ACCURACY  ([!"num:i(CanTimeStamp/CanTimeStampRequiredAccuracy * 1000)"!]UL)
        [!ELSEIF "contains($HR_Time_Src, 'STIMER')"!]
            [!SELECT "node:ref(CanTimeStamp/CanTimeStampExternalTimerReference)"!]
                [!VAR "Gpt_Channel_Tick_Frequency" = "GptChannelTickFrequency"!]
                [!VAR "GptChannelId" = "GptChannelId"!]
                [!VAR "StimerInstance" = "substring-after(node:ref(GptModuleRef)/../../GptStimerModule, 'STIMER_')"!]
                [!VAR "StimerChannel" = "substring-after(node:ref(GptModuleRef)/GptStimerChannel, 'CH_')"!]
            [!ENDSELECT!]
            [!IF "(CanTimeStamp/CanTimeStampRequiredAccuracy) != (1000000000 div $Gpt_Channel_Tick_Frequency)"!]
                [!WARNING!]
                    To convert timestamp value to nanosecond, CanTimeStampRequiredAccuracy should be [!"(1000000000 div $Gpt_Channel_Tick_Frequency)"!](1Ghz/GptChannelTickFrequency)
                [!ENDWARNING!]
            [!ENDIF!]
            [!IF "contains($DerivativeName, 's32n5')"!]
                [!// On S32N Stimer Ip has two instances, one on CRS and other on FSS subsystem. The convention for instance number is 0 for CRS instance and 1 for FSS instance. This refer from Stimer Ip implementation
                [!IF "($CrsCanControllerUseTimestamp = 1)"!]
                    [!VAR "StimerInstance" = "0"!]
                [!ELSEIF "($FssCanControllerUseTimestamp = 1)"!]
                    [!VAR "StimerInstance" = "1"!]
                [!ENDIF!]
            [!ELSEIF "contains($DerivativeName, 's32n7')"!]
                [!// To check for S32N7 platform
            [!ENDIF!]
            #define CAN_43_FLEXCAN_TS_STIMER_USED
            #define CAN_43_FLEXCAN_TS_GPT_CHANNEL_ID  ([!"num:i($GptChannelId)"!]U)
            #define CAN_43_FLEXCAN_TS_STIMER_INSTANCE  ([!"num:i($StimerInstance)"!]U)
            #define CAN_43_FLEXCAN_TS_STIMER_CHANNEL  ([!"num:i($StimerChannel)"!]U)
            #define CAN_43_FLEXCAN_TS_STIMER_TICK_PER_SECOND ([!"num:i($Gpt_Channel_Tick_Frequency)"!]U)
            #define CAN_43_FLEXCAN_TS_STIMER_ACCURACY  ([!"num:i(CanTimeStamp/CanTimeStampRequiredAccuracy * 1000)"!]UL)
        [!ENDIF!]
    [!ENDIF!]
[!ENDIF!]

/**
*   @brief      Has external timer used for timestamp
*/
#define         CAN_43_FLEXCAN_TS_EXTERNAL_TIMER_USED[!WS "4"!][!IF "$external_timer_used = 1"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      The definition used for guarding GetUserId/MultiPartition
*/
#define CAN_43_FLEXCAN_MULTIPARTITION_ENABLED[!WS "4"!][!IF "num:i(count(./CanEcucPartitionRef/*)) > 0"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Define if global variables need to be placed in non-cache area or not
*/
#define CAN_43_FLEXCAN_NO_CACHE_NEEDED[!WS "4"!][!IF "num:i(count(./CanEcucPartitionRef/*)) > 1"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable Development Error Detection and Notification
*/
#define CAN_43_FLEXCAN_DEV_ERROR_DETECT[!WS "4"!][!IF "./CanDevErrorDetect = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable support Can_GetVersionInfo API
*/
#define CAN_43_FLEXCAN_VERSION_INFO_API[!WS "4"!][!IF "./CanVersionInfoApi = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable support Can_SetBaudrate API
*/
#define CAN_43_FLEXCAN_SET_BAUDRATE_API[!WS "4"!][!IF "node:exists(./CanSetBaudrateApi) and (node:value(./CanSetBaudrateApi) = 'true')"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable support Can_AbortMb API
*/
#define CAN_43_FLEXCAN_ABORT_MB_API[!WS "4"!][!IF "node:exists(./CanApiEnableMbAbort) and (node:value(./CanApiEnableMbAbort) = 'true')"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable LPdu Callout Function
*/
#define CAN_43_FLEXCAN_LPDU_CALLOUT_FUNC_ENABLE[!WS "4"!][!IF "node:exists(./CanLPduReceiveCalloutFunction) and (normalize-space(./CanLPduReceiveCalloutFunction) != 'NULL_PTR')"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable Extended Range of Can Hw Object
*/
#define CAN_43_FLEXCAN_MBCOUNTEXTENSION[!WS "4"!][!IF "./CanMBCountExtensionSupport = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Instance of the Can Hw unit
*/
#define CAN_43_FLEXCAN_INSTANCE[!WS "4"!]((uint8)[!"num:i(./CanIndex)"!]U)

/**
*   @brief      Enable/Disable support Dual Clock Mode
*/
#define CAN_43_FLEXCAN_DUAL_CLOCK_MODE[!WS "4"!][!IF "./CanEnableDualClockMode = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable support Listen Only Mode
*/
#define CAN_43_FLEXCAN_LISTEN_ONLY_MODE[!WS "4"!][!IF "node:exists(./CanListenOnlyModeApi) and (node:value(./CanListenOnlyModeApi) = 'true')"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
* @brief        Enable/Disable LPdu Receive callout function support
*/
#define CAN_43_FLEXCAN_LPDU_CALLOUT_SUPPORT[!WS "4"!][!IF "node:exists(./CanLPduReceiveCalloutFunction[. != 'NULL_PTR'])"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]
#define CAN_43_FLEXCAN_LPDU_CALLOUT_FUNC_CALLED[!WS "4"!][!IF "node:exists(./CanLPduReceiveCalloutFunction)"!][!"normalize-space(./CanLPduReceiveCalloutFunction)"!][!ELSE!]NULL_PTR[!ENDIF!][!CR!]

/**
* @brief        Enable/Disable L-PDU HRH Extend Support
*/
#define CAN_43_FLEXCAN_LPDU_HRH_EXTEND_SUPPORT[!WS "4"!][!IF "node:exists(./CanLPduReceiveCalloutFunction[. != 'NULL_PTR']) and node:exists(./LPduHrhExtendSupport[. = 'true'])"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Symbolic Name generated for CanMainFunctionRWPeriods
*/
[!VAR "Index" = "0"!]
[!LOOP "./CanMainFunctionRWPeriods/*"!]
    #define [!"@name"!][!WS "4"!][!"num:i($Index)"!]U
[!VAR "Index" = "$Index + 1"!]
[!ENDLOOP!]

/**
*   @brief      Period for cyclic call of Main Function Read/Write
*/
[!VAR "MainFuncPeriodCount" = "num:i(count(./CanMainFunctionRWPeriods/*))"!]
[!IF "$MainFuncPeriodCount > 0"!]
    [!IF "$MainFuncPeriodCount = 1"!]
        #define CAN_43_FLEXCAN_MAINFUNCTION_MULTIPLE_WRITE[!WS "4"!](STD_OFF)
        #define CAN_43_FLEXCAN_MAINFUNCTION_MULTIPLE_READ[!WS "4"!](STD_OFF)
        [!IF "node:exists(../CanConfigSet/CanHardwareObject/*[./CanObjectType = 'RECEIVE']/CanMainFunctionRWPeriodRef)"!]
            #define CAN_43_FLEXCAN_MAINFUNCTION_READ_PERIOD[!WS "4"!]([!"./CanMainFunctionRWPeriods/*[1]/CanMainFunctionPeriod"!]F)
        [!ENDIF!]
        [!IF "node:exists(../CanConfigSet/CanHardwareObject/*[./CanObjectType = 'TRANSMIT']/CanMainFunctionRWPeriodRef)"!]
            #define CAN_43_FLEXCAN_MAINFUNCTION_WRITE_PERIOD[!WS "4"!]([!"./CanMainFunctionRWPeriods/*[1]/CanMainFunctionPeriod"!]F)
        [!ENDIF!]
    [!ELSE!]
        [!VAR "PeriodReadFlag" = "0"!]
        [!VAR "PeriodWriteFlag" = "0"!]
        [!LOOP "./CanMainFunctionRWPeriods/*"!]
            [!VAR "PeriodName" = "node:name(.)"!]
            [!VAR "PeriodVal" = "./CanMainFunctionPeriod"!]
            [!SELECT "../../../CanConfigSet/CanHardwareObject"!]
                [!IF "num:i(count(./*[./CanObjectType = 'RECEIVE']/CanMainFunctionRWPeriodRef[name(node:ref(.)) = $PeriodName])) > 0"!]
                    [!VAR "PeriodReadFlag" = "num:i($PeriodReadFlag + 1)"!]
                    #define CAN_43_FLEXCAN_MAINFUNCTION_READ_PERIOD_[!"$PeriodName"!][!WS "4"!]([!"$PeriodVal"!]F)
                [!ENDIF!]
                [!IF "num:i(count(./*[./CanObjectType = 'TRANSMIT']/CanMainFunctionRWPeriodRef[name(node:ref(.)) = $PeriodName])) > 0"!]
                    [!VAR "PeriodWriteFlag" = "num:i($PeriodWriteFlag + 1)"!]
                    #define CAN_43_FLEXCAN_MAINFUNCTION_WRITE_PERIOD_[!"$PeriodName"!][!WS "4"!]([!"$PeriodVal"!]F)
                [!ENDIF!]
            [!ENDSELECT!]
        [!ENDLOOP!]
        #define CAN_43_FLEXCAN_MAINFUNCTION_MULTIPLE_WRITE[!WS "4"!][!IF "$PeriodWriteFlag != 0"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]
        #define CAN_43_FLEXCAN_MAINFUNCTION_MULTIPLE_READ[!WS "4"!][!IF "$PeriodReadFlag != 0"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]
    [!ENDIF!]
[!ELSE!]
    #define CAN_43_FLEXCAN_MAINFUNCTION_MULTIPLE_WRITE[!WS "4"!](STD_OFF)
    #define CAN_43_FLEXCAN_MAINFUNCTION_MULTIPLE_READ[!WS "4"!](STD_OFF)
[!ENDIF!]

/**
*   @brief      Period for cyclic call of Main Function Mode
*/
#define CAN_43_FLEXCAN_MAINFUNCTION_MODE_PERIOD[!WS "4"!]([!"./CanMainFunctionModePeriod"!]F)

[!IF "node:exists(./CanMainFunctionBusoffPeriod)"!]
/**
*   @brief      Period for cyclic call of Main Function Bus Off
*/
#define CAN_43_FLEXCAN_MAINFUNCTION_BUSOFF_PERIOD[!WS "4"!]([!"./CanMainFunctionBusoffPeriod"!]F)
[!ENDIF!]

[!IF "node:exists(./CanMainFunctionWakeupPeriod)"!]
/**
*   @brief      Period for cyclic call of Main Function Wakeup
*/
#define CAN_43_FLEXCAN_MAINFUNCTION_WAKEUP_PERIOD[!WS "4"!]([!"./CanMainFunctionWakeupPeriod"!]F)
[!ENDIF!]

/**
*   @brief      Supporting Pretended Networking
*/
#define CAN_43_FLEXCAN_PUBLIC_ICOM_SUPPORT[!WS "4"!]([!IF "(ecu:get('Can.CanConfigSet.CanPretendedNetworking') = 'STD_ON') and (./CanPublicIcomSupport = 'true')"!]STD_ON[!ELSE!]STD_OFF[!ENDIF!])
[!ENDSELECT!]

[!SELECT "CanConfigSet"!]
/**
*   @brief      Number Of Can Controller Config
*/
#define CAN_43_FLEXCAN_CONTROLLER_CONFIG_COUNT[!WS "4"!]([!"num:i(count(./CanController/*))"!]U)[!CR!]

/**
*   @brief      Number Of HardwareObject Config
*/
#define CAN_43_FLEXCAN_HWOBJECT_CONFIG_COUNT[!WS "4"!]((Can_HwHandleType)[!"num:i(count(./CanHardwareObject/*))"!]U)[!CR!]

/**
*   @brief      Symbolic Name generated for Can Controller
*/
[!LOOP "node:order(./CanController/*, './CanControllerId')"!]
    #define Can_43_FLEXCANConf_CanController_[!"@name"!][!WS "4"!]((uint8)[!"num:i(./CanControllerId)"!]U)[!CR!]
[!ENDLOOP!]

/**
*   @brief      Symbolic Name generated for Can HardwareObject
*/
[!LOOP "node:order(./CanHardwareObject/*, './CanObjectId')"!]
    #define Can_43_FLEXCANConf_CanHardwareObject_[!"@name"!][!WS "4"!]((Can_HwHandleType)[!"num:i(./CanObjectId)"!]U)[!CR!]
[!ENDLOOP!]

/**
*   @brief      Enable/Disable support  Can_CheckWakeup API
*/
#define CAN_43_FLEXCAN_CHECK_WAKEUP_API[!WS "4"!][!IF "node:exists(./CanController/*[./CanWakeupFunctionalityAPI = 'true'])"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Can Tx Polling support
*/
#define CAN_43_FLEXCAN_TX_POLLING_SUPPORT[!WS "4"!][!IF "node:exists(./CanController/*[./CanTxProcessing != 'INTERRUPT'])"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Can Rx Polling support
*/
#define CAN_43_FLEXCAN_RX_POLLING_SUPPORT[!WS "4"!][!IF "node:exists(./CanController/*[./CanRxProcessing != 'INTERRUPT'])"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Can Bus Off Polling support
*/
#define CAN_43_FLEXCAN_BUSOFF_POLLING_SUPPORT[!WS "4"!][!IF "node:exists(./CanController/*[./CanBusoffProcessing = 'POLLING'])"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Can Wakeup Polling support
*/
#define CAN_43_FLEXCAN_WAKEUP_POLLING_SUPPORT[!WS "4"!][!IF "node:exists(./CanController/*[./CanWakeupProcessing = 'POLLING'])"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Can Wakeup support
*/
#define CAN_43_FLEXCAN_WAKEUP_SUPPORT[!WS "4"!][!IF "node:exists(./CanController/*[./CanWakeupSupport = 'true'])"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Can Rx/Tx common interrupt support
*/
[!VAR "MbIntFlag" = "0"!]
[!LOOP "node:order(./CanController/*, './CanControllerId')"!]
    [!VAR "CtrlID" = "./CanControllerId"!]
    [!VAR "RxIntFlag" = "0"!]
    [!VAR "TxIntFlag" = "0"!]
    [!IF "./CanRxProcessing != 'POLLING'"!]
        [!VAR "RxIntFlag" = "1"!]
    [!ELSEIF "./CanTxProcessing != 'POLLING'"!]
        [!VAR "TxIntFlag" = "1"!]
    [!ENDIF!]
    [!IF "num:i($RxIntFlag) = 1 or num:i($TxIntFlag) = 1"!]
        [!VAR "MbIntFlag" = "1"!]
    [!ENDIF!]
[!ENDLOOP!]


/**
*   @brief      The definition was represented for at least one Hw Object enabled trigger transmit.
*/
#define CAN_43_FLEXCAN_TRIGGER_TRANSMIT_USED[!WS "4"!][!IF "node:exists(./CanHardwareObject/*[./CanTriggerTransmitEnable = 'true'])"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]


[!ENDSELECT!]

[!NOCODE!]
[!IF "((IMPLEMENTATION_CONFIG_VARIANT != 'VariantPostBuild') and (variant:size()>1)) or (IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild')"!]
[!CODE!]
/**
*   @brief      External Structures generated by Can_43_FLEXCAN_PBCfg.
*/
#define CAN_43_FLEXCAN_CONFIG_EXT \[!CR!]
[!ENDCODE!]
    [!INDENT "4"!]
    [!IF "var:defined('postBuildVariant')"!]
        [!VAR "variantIndex"="0"!]
        [!VAR "variantNumber"="variant:size()"!]
        [!LOOP "variant:all()"!]
            [!VAR "variantIndex"="$variantIndex + 1"!]
            [!CODE!]CAN_43_FLEXCAN_CONFIG_[!"text:toupper(.)"!]_PB [!IF "$variantIndex < $variantNumber"!]\[!ENDIF!][!CR!][!ENDCODE!]
        [!ENDLOOP!]
    [!ELSE!]
        [!CODE!]CAN_43_FLEXCAN_CONFIG_PB[!CR!][!ENDCODE!]
    [!ENDIF!]
    [!ENDINDENT!]
[!ENDIF!]
[!ENDNOCODE!]
[!ENDINDENT!]


#ifdef __cplusplus
}
#endif

/** @} */

#endif /* _CAN_43_FLEXCAN_CFG_H_ */
